### ISSUE TITLE
Check for passed in regions

### ISSUE THREAD

**Issue by mikejolley** [Astoundify/wp-job-manager-regions#27]
Alerts has regions support and passes in search_region to the get_job_listings function.

However, https://github.com/Astoundify/wp-job-manager-regions/blob/master/wp-job-manager-locations.php#L122 no longer looks for this (it only tries to detect params) so this passed in arg is no longer detected.

Can you guys add an extra check for this?

**Comment by adampickering** [comment]
Maybe something we can get @Astoundify/dev-jeroen-sormani to look at adding @spencerfinnell

**Comment by JeroenSormani** [comment]
Added a PR to check for WPJM Alerts

@mikejolley Thanks for adding me to the WP JM repo!

**Comment by brianheap** [comment]
@JeroenSormani @spencerfinnell This fix doesn't solve the problem when sending the emails unfortunately. It only fixes it when you view the alert results on the website. The jobs in the email are still not filtered correctly for the region specified :-(

**Comment by mikejolley** [comment]
@JeroenSormani not quite what I meant.

You notice you have a 

`
if ( isset( $_REQUEST[ 'form_data' ] ) ) {
`

This means you only hook in and filter jobs when thats set. I'd like if if you also checked for an $args[ 'search_region' ]  then I can pass it in to you at any time.

**Comment by JeroenSormani** [comment]
@mikejolley Ahh, misunderstood.
When viewing the contents of $args I don't see any vars that might come from the Alerts plugin, is that right?

When I'm changing it to `$args['search_region']` the filtering on the site also stops working as that param doesn't exist.

Would this work for you? https://github.com/JeroenSormani/wp-job-manager-regions/blob/a5298329af78db62fae93214cc357e52fe1afd7e/wp-job-manager-locations.php#L163-L176

**Comment by mikejolley** [comment]
Yes I think so - so its only used if set.
