### ISSUE TITLE
Adding new region from the job listing page doesn't always work. 

### ISSUE THREAD

**Issue by adampickering** [Astoundify/wp-job-manager-regions#28]
If you add a region that has a , symbol from the job listing it won't add it, but it if you add from the job regions edit/add screens it will allow you to add it.

See gif:

![adding-region](https://cloud.githubusercontent.com/assets/746776/5965643/a9b235ce-a7cb-11e4-8b04-fc08bd15c35b.gif)

Maybe this is something we can get @Astoundify/dev-jeroen-sormani to work on as well as  @spencerfinnell

**Comment by spencerfinnell** [comment]
WordPress issue. Nothing to do with e plugin.

**Comment by adampickering** [comment]
poo poo
