### ISSUE TITLE
Integrate with Resume Manager

### ISSUE THREAD

**Issue by rali14** [Astoundify/wp-job-manager-regions#34]
Integrate regions with the Resume manager plugin to allow for predefined regions.

**Comment by benjaminprojas** [comment]
@rali14 would this just be a dropdown in addition to the location field? 
![](https://www.dropbox.com/s/o0mq23q535vpbtt/Screenshot%202016-04-28%2021.16.08.png?dl=1)

Or would it be instead of? Any more info on how this is supposed to work would be awesome.

**Comment by spencerfinnell** [comment]
It is in addition to. See how it functions on standard job listings. It is a field on the submission form as well as replacing the filter on the search (if enabled). 

Should duplicate exactly what happens for jobs.

**Comment by benjaminprojas** [comment]
@spencerfinnell awesome, thanks

**Comment by benjaminprojas** [comment]
@spencerfinnell Okay, I was adding this in based on how it works with Job Manager Listings, but from what I can tell, the integration is incomplete with that.  I don't see it get saved in the postmeta, and I don't see it on the backend anywhere.  Am I missing something?

**Comment by spencerfinnell** [comment]
Need to create a new taxonomy for resumes: https://github.com/Astoundify/wp-job-manager-regions/blob/master/includes/class-taxonomy.php#L14

Then for some reason the existing taxonomy was added to resumes which is incorrect: https://github.com/Astoundify/wp-job-manager-regions/blob/master/includes/class-template.php#L56 -- needs to be updated. 

Then duplicate/apply these filters the same way for resumes: https://github.com/Astoundify/wp-job-manager-regions/blob/master/wp-job-manager-locations.php#L72-L78

**Comment by benjaminprojas** [comment]
@spencerfinnell I couldn't find a comparable function in resumes to this:

https://github.com/Astoundify/wp-job-manager-regions/blob/master/wp-job-manager-locations.php#L79

Otherwise, I tried to duplicate the functions and update based on what would work with resumes.  Let me know what you think.
