### ISSUE TITLE
Save Selection When Previewing/Editing

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-regions#36]

**Comment by brianheap** [comment]
If you mean that when adding a job, then going back to edit it and the job_region select box is not prefilled, this was fixed with https://github.com/Astoundify/wp-job-manager-regions/commit/13e9fce2b40391b998270c8f0bd6bb2e036ab5fd

**Comment by spencerfinnell** [comment]
Confirmed.
