### ISSUE TITLE
search by region instead of location with job alert doesnt work !!!

### ISSUE THREAD

**Issue by jathagrimon** [Astoundify/wp-job-manager-regions#39]
Hi there,

it schould be possible to:
- filter the whole search by regions - works
- search by regions into the job alert - doesnt work
- takeover the regions by action "Send me a mail by jobs like these" - doesnt work

I want use regions instead of location. So i have activated the regions and the filter shows no location-selector.

Problems:
1. When i create an alert and filter by specified regions brings the result everytime all jobs as return. Thats wrong why does the filter nor work?

2. If i show a job as blog and click at the bottom "Send me a mail by jobs like these" ( i dont know the correct words in english -> used language is german) then the filter is shown but does not check all of the selected regions from the source-job. Only one region is selected.

i need a solution asap because we want go live with the page.

Thx

**Comment by mikejolley** [comment]
@spencerfinnell I pinged you on slack about this, but yes its a bug.

> Hey FYI this has broken alerts https://github.com/Astoundify/wp-job-manager-regions/blob/master/wp-job-manager-locations.php#L122-L180
> 
> $args contains the post query args, not the args passed to the get_listings function. Needs a 2nd argument passed to the filter.

**Comment by spencerfinnell** [comment]
The Alerts addon is only selecting the first region when generating the links: 

https://github.com/Automattic/wp-job-manager-alerts/blob/323954197c1874ae91e33ec1ea335291caccd49e/wp-job-manager-alerts.php#L213

Fixed the query though when viewing results.

**Comment by jathagrimon** [comment]
great, now it works fine. I've tested. THANKS
