### ISSUE TITLE
Filter by region setting remains after deactivation

### ISSUE THREAD

**Issue by rali14** [Astoundify/wp-job-manager-regions#40]
The filter by region option setting is saved even after the plugin is deactivated: https://i.imgur.com/DP513uO.png

This causes the radius filter to disappear without any way to enable it without first activating the theme.

Need to disable radius only if Pre Defined regions is active AND filter by region is selected.

**Comment by spencerfinnell** [comment]
This is fixed in Listify via https://github.com/Astoundify/listify/commit/b83fa4bdf4cdc4bddbea6497f99e7c43bfe4f484
