### ISSUE TITLE
BUG: incompatibility with WP Job Manager Alerts

### ISSUE THREAD

**Issue by wpmagik** [Astoundify/wp-job-manager-regions#43]
This looks like an easy fix. Everywhere in your code where you add tax_query, you need to check $region var. Otherwise in job alerts there are always empty results when regions field is empty. I don't know why it works in default job_alerts shortcode, but anyway:

if( $region )
{
	$query_args[ 'tax_query' ][] = array( /* ... */ );
}

**Comment by spencerfinnell** [comment]
See #42
