### ISSUE TITLE
Issue with "Recent Jobs" widget

### ISSUE THREAD

**Issue by adamhurlebaus** [Astoundify/wp-job-manager-regions#47]
I've been having the same issue as listed [here](https://wordpress.org/support/topic/widget-not-working-properly?replies=12) where the styling is distorted in the recent jobs widget.  Specifically noted in the last reply is what happens to the widget.  This only occurs when the predefined regions plugin is activated.  

I believe the reason is that [this line](https://github.com/Astoundify/wp-job-manager-regions/blob/master/includes/class-template.php#L108) uses [get_the_term_list](https://codex.wordpress.org/Function_Reference/get_the_term_list) which according to the documentation inserts anchor tags around every item it outputs.  That's exactly what's occurring in the recent jobs widget when this plugin is active.

To fix this, I removed the if/else portion on line 108 [see pull request](https://github.com/adamhurlebaus/wp-job-manager-regions/commit/24cbb7be3e7a3272c5bd59ff33bc64c37d17dd56) and completely excluded the check for "is_singular" and any code that might have executed as a result and the styling was not distorted in the widget.

That was a quick fix for me, but I think a more elegant solution is to only use the is_singular code listed above if the widget is not present on the page.  If you still believe the existing code is necessary for single pages, is it somehow possible to exclude the way the location is returned only to the widget, but still keep the same code for the full job listing?

**Comment by spencerfinnell** [comment]
This looks like it was worked around in WP Job Manager core.
