### ISSUE TITLE
Add Option to Disable Filtering Location Output

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-regions#49]
Should be a checkbox on by default.

**Comment by benjaminprojas** [comment]
I am a little confused as to what this is referring to.  More context?

Regions doesn't have its own tab currently, is this okay to just add another option to the main listings settings page or do we want to create a "Regions" tab in the settings?

**Comment by spencerfinnell** [comment]
With the plugin active this filter is always added: https://github.com/Astoundify/wp-job-manager-regions/blob/94711e228d93c8659c5aa505bbb90a667677c079/includes/class-template.php#L7

So any calls to `the_job_location()` (a WP Job Manager core function) will be filtered to return the selected Region, not the entered location (`_job_location`) field. 

I want an option that marks this as the default behavior with the availability to disable it (uncheck it).

**Comment by benjaminprojas** [comment]
cool, makes sense. thanks!
