### ISSUE TITLE
Add a Placeholder

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-regions#50]
Instead of the first region being the automatically selected option.

**Comment by benjaminprojas** [comment]
Are we referring to the "All Regions" option?  What should the placeholder say?

![](https://www.dropbox.com/s/8z3hi51g594nb41/Screenshot%202016-04-28%2021.10.37.png?dl=1)

**Comment by spencerfinnell** [comment]
This is referring to the submission form. Possible now that https://github.com/Automattic/WP-Job-Manager/pull/565 is in. 

*note to self*: Make more descriptive issues.
