### ISSUE TITLE
Change region drop-down to chosen drop-down styling.

### ISSUE THREAD

**Issue by adampickering** [Astoundify/wp-job-manager-regions#52]
Is this something @benjaminprojas could take care of @spencerfinnell 

From this
![screen shot 2016-06-19 at 9 27 59 pm](https://cloud.githubusercontent.com/assets/746776/16181140/8ffa0f02-3664-11e6-9efa-19d4d4150dc5.jpg)

To this

![screen shot 2016-06-19 at 9 28 03 pm](https://cloud.githubusercontent.com/assets/746776/16181142/91369048-3664-11e6-84c4-863cfd027e2d.jpg)

**Comment by spencerfinnell** [comment]
Looks like a bug because it is already in place: https://github.com/Astoundify/wp-job-manager-regions/blob/c7f136f47fb7de8573a100ff07655137355d1ee2/assets/js/main.js#L27

**Comment by adampickering** [comment]
Hey, could you take a look at this on monday please @benjaminprojas

**Comment by adampickering** [comment]
Hey, could you take a look at this when you have time please @turtlepod might be also good to give the plugin a quick audit.

**Comment by spencerfinnell** [comment]
Not an issue in master.

**Comment by adampickering** [comment]
So it just needs pushing to WordPress.org?

**Comment by spencerfinnell** [comment]
Yeah

**Comment by turtlepod** [comment]
Seem to be working fine. Here's the screenshot:
https://dl.dropboxusercontent.com/u/32880842/etc6/job-manager-select-region.png
