### ISSUE TITLE
apikey

### ISSUE THREAD

**Issue by nbastreet** [Astoundify/wp-job-manager-regions#53]
How can i use My own premium apikey on this plugin?

**Comment by spencerfinnell** [comment]
There is no need for this plugin. It does not use any Google mapping functionality. What are you referring to?

**Comment by nbastreet** [comment]
look at this:
http://googlegeodevelopers.blogspot.com.au/2016/06/building-for-scale-updates-to-google.html
i want use wp job manager extended location that have search suggest, can i use this plugin and extended without any api?

**Comment by spencerfinnell** [comment]
This is not for that plugin. The latest version of the Extended Location plugin includes a setting in Job Listings ▸ Settings ▸ Location Settings.

**Comment by nbastreet** [comment]
setting for using api and have search suggestion?
what is latest version of extended location plugin?

**Comment by spencerfinnell** [comment]
2.5.2 -- Please contact https://astoundify.com/support for more information regarding this subject. This is not the appropriate place for this discussion.
