### ISSUE TITLE
Select Region Label on Job Type Field

### ISSUE THREAD

**Issue by rali14** [Astoundify/wp-job-manager-regions#56]
https://cloudup.com/cMQHrIsBOky

**Comment by spencerfinnell** [comment]
Fixed in https://github.com/Astoundify/wp-job-manager-regions/commit/55563853a03adaefdc477de49c11371a02a62345

https://github.com/Astoundify/wp-job-manager-regions/releases/tag/1.12.0

Fixes it.

**Comment by rali14** [comment]
![giphy](https://cloud.githubusercontent.com/assets/3098523/22081288/09e88324-dd91-11e6-92ed-8d23485a17d4.gif)
