### ISSUE TITLE
Region Selection on Listing/ Job Submission form.

### ISSUE THREAD

**Issue by FernandoSalinas33** [Astoundify/wp-job-manager-regions#57]
Lets say a user has a ridiculous list or regions, maybe 5K, on a mobile device the list is ongoing.
Would there be any way to improve the selection of regions on a mobile device instead of having to scroll through a never-ending list?

**Comment by spencerfinnell** [comment]
The Chosen library that is packaged with WP Job Manager does not support any special selection on mobile devices so not sure how this could be improved. 

https://harvesthq.github.io/chosen/
