### ISSUE TITLE
Jobify search bar no results when using more than one keywords

### ISSUE THREAD

**Issue by Bertsi** [Astoundify/wp-job-manager-regions#58]
Im using jobify for my job listings. When I use the search bar and type in more then one keyword in the search-field, zero jobs get found, even when I use two exact keywords that appear in the headline of a certain job_posting. When I use only one keyword, I get several matches what is fine. But with more than one keyword its always zero matches. I tried it with comma and semicolon between the keywords but it makes no difference. Can anyone help me with that issue. Thanks a lot!

**Comment by spencerfinnell** [comment]
Please post this issue here: http://github.com/automattic/wp-job-manager
