### ISSUE TITLE
How to translate Regions

### ISSUE THREAD

**Issue by gabrymusix** [Astoundify/wp-job-manager-regions#65]
Hello,
how is possible to translate Regions and Categories names, with Polylang or Loco translate?
thanks for help

**Comment by turtlepod** [comment]
I never fully tested it, but I think it will work fine (for polylang, not sure about Loco Translate, I never use it).
You will also need to translate all your listings too and set the region based on each language.

e.g English listing need to be assigned to English Region.

Let me know if it's working for you :)

**Comment by gabrymusix** [comment]
Dear,
thanks for reply but i didn't understood how to proceed. I'm working on a customer's multi-language  website.
Do i buy polylang pro?
I need to translate in Resumes: 
- resume Regions
- resume categories
... in Job Listings:
- job regions 
- job categories

thanks for kind reply

**Comment by turtlepod** [comment]
I think you can just translate it like regular taxonomy, If you have problem in setup Polylang, please contact the developer or support forum https://wordpress.org/support/plugin/polylang

I don't think you need Polylang Pro, unless there's a features you need (their Premium Support maybe ?)

**Comment by gabrymusix** [comment]
ok resolved,
thanks for support :-)
