### ISSUE TITLE
Bug Regions filter returns 0 results when not used.

### ISSUE THREAD

**Issue by FernandoSalinas33** [Astoundify/wp-job-manager-regions#67]
Since 1.15.0 Searching listings and jobs return 0 results when the region filter is not used: https://cloudup.com/cBlF2ijHbcv

If you select a Region, results appear.

**Comment by spencerfinnell** [comment]
https://github.com/Astoundify/wp-job-manager-regions/commit/633883d2f9d296fb5df4b4a1257c1e239e70d349
