### ISSUE TITLE
Search by region returns all jobs/regions after WPJM 1.33

### ISSUE THREAD

**Issue by Dubaidogfish** [Astoundify/wp-job-manager-regions#74]
Regions 1.17.4
WPJM 1.33 & 1.33.1 beta
(Themes: Jobify & WP 2019)

Set up search by regions dropdown.
Expected and actual result with Regions 1.17.4 & WPJM 1.32.3 is jobs in region returned.
Actual result in WPJM 1.33 - all jobs in all regions returned regardless of region in dropdown chosen (same including keyword/no keyword).

I have tried this on 2019 theme preview and get same result.

Others having same issue: https://wordpress.org/support/topic/search-by-regions-and-keywords-not-working-since-1-33-0/

Thanks.

**Comment by Dubaidogfish** [comment]
Knocking the $ off `$form_data:_.serialize()` in plugins/wp-job-manager/assets/js/ajax-filters.min.js seems to fix it as suggested by @wpsolr in https://wordpress.org/support/topic/search-by-regions-and-keywords-not-working-since-1-33-0/

**Comment by andreilupu** [comment]
Hello, and thanks for raising this issue.

The dollar sign will be removed in the next version of WP Job Manager and I think we should leave it this way since it will be reverted here: https://github.com/Automattic/WP-Job-Manager/pull/1793

I'll close it, for now, thanks!
